version: '3'
services:
  app:
    build:
      context: ./docker/vue/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    command: /bin/sh